### ISSUE TITLE
find_vm uses just hostname delta, vSphere searchIndex matches on FQDN

### ISSUE THREAD

**Issue by aeria** [puppetlabs/vmpooler#141]
In my vSphere 5.5 environment I have found an issue where my VMs which have fully registered DNS hostnames were not validating. The step just before the TCP check was failing, find_vm.

e.g. vmpooler will create a a vm called 'nq6ppokwh7f6poz'
I then register (say via nsupdate) this new host to a DNS server under the desired zone. (.lan)
nq6ppokwh7f6poz.lan would be the FQDN

Additionally, the spawned VM gets its hostname set querying vmtoolsd for the correct guestInfo.hostName

```
$ hostname nq6ppokwh7f6poz.lan
```

Any request using just the hostname to vSphere using PowerCLI or in the below case rbvmomi's CLI results in nil - and eventually once timeout is reached the VM is torn down and another setup.

```
10.10.67.19> si.content.searchIndex.FindByDnsName({vmSearch: true, dnsName: 'egcs436v63psg1q'})
nil
10.10.67.19> si.content.searchIndex.FindByDnsName({vmSearch: true, dnsName: 'egcs436v63psg1q.lan'})
VirtualMachine("vm-1101")
```

I've also included my startup script that may be useful to throw in the doco for those that do not have better/control over DNS & DHCP

```
#!/bin/sh -

# The below  can be removed if your DHCP server manages this better
DNSSEARCH=MY_DNS_SUFFIX
DNS=MY_DNS_SERVER
echo "Update resolv.conf"
echo "search $DNSSEARCH" > /etc/resolv.conf
echo "nameserver $DNS" >> /etc/resolv.conf


# Grab IP
IPADDRESS=`ip addr show ens160 | sed -En 's/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`

# Set Hostname
HOSTNAME=`vmtoolsd --cmd "info-get guestinfo.hostname"`
FQDN="$HOSTNAME.lan"

echo "Setting Hostname to $FQDN"
hostname $FQDN


# Add to DNS
echo "Create DNS entry for $FQDN with IP $IPADDRESS"

echo "server foreman.lan" > /tmp/nsupdate
echo "zone lan." > /tmp/nsupdate
echo "update delete $FQDN" >> /tmp/nsupdate
echo "update add $FQDN 60 A $IPADDRESS" >> /tmp/nsupdate
echo "send" >> /tmp/nsupdate

nsupdate -k /etc/rndc.key -v /tmp/nsupdate
```

**Comment by frozenfoxx** [comment]
I am experiencing the same issue.  Due to using OS X guests the hostname of the guests are set differently, but their FQDN and IP are definitely visible in my vSphere 5.5 setup.

I added some debug lines in the *_check_pending_vm()* method and it seems the *host* variable is getting set to nil, causing the same  behavior of clone -> pending -> timeout -> teardown.

```
    def _check_pending_vm(vm, pool, timeout)
      host = $vsphere[pool].find_vm(vm)

      $logger.log('d', "[ ] vm in _check_pending_vim is #{vm}")
      $logger.log('d', "[ ] pool in _check_pending_vim is #{pool}")
      $logger.log('d', "[ ] host in _check_pending_vim is #{host}")
      $logger.log('d', "[ ] [#{vm['template']}] '#{vm}' reports an IP of #{vm.guest.ipAddress}'")
```

**Comment by mattkirby** [comment]
Vmpooler by default assumes that DNS search domains are set. If you specify the domain for the VM in the vmpooler configuration file then that will be used when looking it up.
