### ISSUE TITLE
vsphere_helper.rb: find_least_used_host should warn if no suitable hosts are found

### ISSUE THREAD

**Issue by Renelast** [puppetlabs/vmpooler#164]
The find_least_used_host function in the lib/vspehere_helper.rb file should throw some sort of error or at least log if it was unable to find a suitable host in it's ESX cluster.

Right now this function only considers to select hosts in a cluster that have an overall status of "green"
As it happens in our infrastructure, sometimes an alert is triggered on the datacenter (or esx cluster) that causes all the host to be in "yellow" state for a while (at least until the alerts are cleared).
If that is the case then vmpooler just stops deploying new servers without given any feedback as to why.

One could also make the case for letting this function consider hosts in "yellow" state as well since yellow does not mean the hosts are completely unusable.

**Comment by mattkirby** [comment]
When #242 lands it will resolve this if you're using vmpooler managed host selection. Alternately, if deferring host selection to vcenter then hosts in the yellow state still may be able to receive new VMs.

**Comment by mattkirby** [comment]
Vmpooler will now log a more useful message in the case there are no available hosts to target for deployment.
