### ISSUE TITLE
Add API to clone new VM from existing VM snapshot

### ISSUE THREAD

**Issue by KevinCorcoran** [puppetlabs/vmpooler#165]
I'd like to be able to create/retrieve a new VM based on an existing VM snapshot.  This is useful in situations when you've created a snapshot which captures an important initial state, and want to be able to do multiple things concurrently (on multiple machines) from that state.

**Comment by mattkirby** [comment]
Vmpooler does not provide the capability to clone machines on an ad-hoc basis. For your VM to be the source it needs to be powered off and provide the capability for a newly deployed instance to bootstrap itself. As a result you're better off capturing your desired state and deploying it as a new template.
