### ISSUE TITLE
Feature Request: Add provider support

### ISSUE THREAD

**Issue by cdenneen** [puppetlabs/vmpooler#181]
Allow vmpooler to not only control vsphere backend but openstack, ec2, etc.
I think the vmpooler model is great, just wish it was available to others not using vsphere.

**Comment by sschneid** [comment]
FWIW, I have this functionality (AWS, GCE) in a [fork](https://github.com/sschneid/vmpooler/tree/ec2_pooling), but it is a bit behind `master` at the moment.  I'm hoping to rebase and clean some things up for a future PR.

**Comment by glennsarti** [comment]
It's in the works...It's just a lot of effort to effectively untangle vSphere.

https://github.com/puppetlabs/vmpooler/pull/179 - Initial Work in progress attempt

https://tickets.puppetlabs.com/browse/POOLER-70
https://tickets.puppetlabs.com/browse/POOLER-73

**Comment by glennsarti** [comment]
@sschneid @cdenneen I've started the process.  Any PRs with POOLER-70 will identify the work that's being done.

**Comment by glennsarti** [comment]
@cdenneen This work has been completed and is now merged.

This ticket can be closed.

**Comment by cdenneen** [comment]
I think the work done has prepped the groundwork but I don't think the
dummy provider would be a useable alternate provider.

**Comment by glennsarti** [comment]
Oh no.  the Dummy Provider is not meant as that.  Do you think some docs on how to add a provider would be sufficient?

**Comment by cdenneen** [comment]
Yes I think many of us might be full cloud shops and don't have vSphere so
providing a way to leverage vmpooler with different backends like AWS, GCE,
Azure, Digital Ocean, openstack, etc will help tremendously. While beaker
supports these hypervisors time it takes to spin these up sometimes so
having a quick pool to pull from and reset when complete I think is great
idea.

**Comment by mattkirby** [comment]
Provider support has been added. You can see the vsphere provider as an example of how this is implemented. The gist is your provider needs to sort out providing the capabilities that pool_manager is trying to leverage and then it should be able to leverage the vmpooler application.

**Comment by cdenneen** [comment]
I think we were waiting for working example of another provider (AWS, GCE, Azure) as the dummy one doesn’t explain how to use this added provider support.

**Comment by mattkirby** [comment]
The working provider is https://github.com/puppetlabs/vmpooler/blob/master/lib/vmpooler/providers/vsphere.rb. Our (Puppet) vmpooler instances are all using vsphere as the provider so I don't have any examples of alternate backend providers implemented to offer. Plugging in another provider should be a matter of adding something like the vsphere provider with the capabilities implemented to support pool_manager operations. It's possible there is some vsphere specific stuff still lurking in  pool_manager that will need to change, but that's something that can be sorted out as the need arises.

I'm happy to help if I can with any other specific questions, but I think the vsphere provider should serve as a good working example to start from.
