### ISSUE TITLE
Should exit Threads cleanly

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/vmpooler#193]
Currently the pool_manager exits threads in a very terminal/undeterminstic manner (using Thread.exit).  This can cause problems with inconsistent redis information or hung vSphere operations.

Instead we should be exiting threads as cleanly as possible.  Probably just using a simple global boolean and a whole bunch of `if $global_step then return` type statements.

**Comment by mattkirby** [comment]
There is no longer any code that calls Thread.exit.
