### ISSUE TITLE
No reason why get_snapshot_list is defined in vsphere_helper

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/vmpooler#202]
The method `get_snaphost_list` defined in https://github.com/puppetlabs/vmpooler/blob/master/lib/vmpooler/vsphere_helper.rb#L393-L405 is only called by `find_snapshot` (https://github.com/puppetlabs/vmpooler/blob/master/lib/vmpooler/vsphere_helper.rb#L296-L300).  As `find_snapshot` is only a simple guarding `if` statement, the code in get_snapshot_list should just be moved into `find_snapshot`

Also the name of the method is misleading.  `get_snapshot_list` searches for a snapshot with a name, it does get a list of snapshots.  Moving it into `find_snapshot` makes sense there too.

**Comment by glennsarti** [comment]
UPDATE - So `get_snaphost_list` is a recursive lookup function whereas find_snapshot is the entry point. The method still seems badly named.

**Comment by mattkirby** [comment]
This method is no longer present in vmpooler.
