### ISSUE TITLE
Vsphere connections are always insecure (Ignore cert errors)

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/vmpooler#207]
Due to the following code the connection to vSphere is always insecure;
https://github.com/puppetlabs/vmpooler/blob/master/lib/vmpooler/vsphere_helper.rb#L29
```
insecure: credentials['insecure'] || true
```
This is because `||` is a binary or operator and anything that is `xxx or true` will evaluate to true.

I imagine the original intent was if `credentials['insecure']` is nil then default to true otherwise use `credentials['insecure']`

**Comment by mattkirby** [comment]
true was hardcoded prior to this, but it looks like this isn't much better.

**Comment by glennsarti** [comment]
insecure is jsut to ignore cert errors.  Not as serious as first thought.
https://github.com/vmware/rbvmomi/blob/master/lib/rbvmomi/vim.rb#L24
