### ISSUE TITLE
`find_pool` in vsphere_helper.rb has subtle errors

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/vmpooler#210]
The logic used to traverse the tree uses the object names for traversal, however if two objects have same name e.g. a Folder and a Resource Pool, and are in a particular order find_pool will throw errors.

This is similar to issue https://github.com/puppetlabs/vmpooler/issues/204 .

Perhaps the find_pool code should be using a PropertyCollector to get vCenter to do an inventory search instead.

e.g. http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.pg.doc%2FPG_PropertyCollector.7.1.html

**Comment by mattkirby** [comment]
Find_pool is no longer used. I will submit a PR to remove this.
