### ISSUE TITLE
`get_base_vm_container_from` in `vsphere_helper` ensures the wrong connection

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/vmpooler#212]
In `get_base_vm_container_from` it calls `ensure_connection` with `@connection` instead of the connection that's passed to the function.

This appears to be a typo.

Code:
https://github.com/puppetlabs/vmpooler/blob/master/lib/vmpooler/vsphere_helper.rb#L383

**Comment by mattkirby** [comment]
This has since been fixed.
