### ISSUE TITLE
Any interest in VRA7 support?

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/vmpooler#235]
I can contribute a vra7 provider since I have a direct need to make vmpooler work with vra7.  Would vmpooler be compatible with vra7 since some of the functions don't translate easily from vcenter speak. 

Specifically:

https://github.com/puppetlabs/vmpooler/blob/master/lib/vmpooler/providers/base.rb#L108
https://github.com/puppetlabs/vmpooler/blob/master/lib/vmpooler/providers/base.rb#L118

**Comment by glennsarti** [comment]
In theory yes.  You can just send "dummy" responses for things it doesn't support. e.g. just return true for migration.

I would like to eventually have providers surface their capabilities and then the pool manager can determine what to do, but that's WAAAY off in the distance :-)

**Comment by logicminds** [comment]
I maybe a month or two away from implementing this.  What is the status with #181?   I liked what you wrote so far looks like you just need the time to finish it.

**Comment by mattkirby** [comment]
Provider support is implemented. I have closed #181. If you would like to add a VRA7 provider I'm happy to offer review.

**Comment by andham** [comment]
@logicminds Did you implement a VRA provider?

**Comment by logicminds** [comment]
I did not as my contract with the client at the time ended before I could implement it.  Since I don't run VRA at my house I have no way to develop this.
