### ISSUE TITLE
YAML.safe_load does not work with symbols in config file

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/vmpooler#240]
I have no idea how this ever worked.  YAML.safe_load does not like the usage of symbols in the config file.

```ruby
if ENV['VMPOOLER_CONFIG']
     # Load configuration from ENV
      parsed_config = YAML.safe_load(ENV['VMPOOLER_CONFIG'])
end
```

This throws error `Psych::DisallowedClass:  Tried to load unspecified class: Symbol`

The fix for now is to not use YAML.safe_load and instead just use YAML.load.

**Comment by logicminds** [comment]
There is a separate PR coming soon that fixes this while still using safe_load

**Comment by fwoelm** [comment]
`YAML.safe_load` only supports a limited set of classes by default, such as String, Numeric, and Hash.

If you call safe_load on content that has any other types of classes (such as Symbol), it raises an error. You can explicitly allow other classes by specifying them in an array as a second argument to safe_load. For example, to allow symbols:

```ruby
if ENV['VMPOOLER_CONFIG']
  # Load configuration from ENV
  parsed_config = YAML.safe_load(ENV['VMPOOLER_CONFIG'], [Symbol])
end
```

See more here: http://www.rubydoc.info/stdlib/psych/Psych.safe_load

PS: Looks like you already have this solution implemented in your latest commits.  Just wanted to document it here for anyone who — like myself — comes to this page after searching DuckDuckGo for this error.
