### ISSUE TITLE
jruby 1.7.8 does not support safe_load

### ISSUE THREAD

**Issue by adamdav** [puppetlabs/vmpooler#243]
When testing against jruby 1.7.8 which is defined in the travis file, loading of the yaml fails because safe_load did not exist in that version of jruby. 

1.7.8 is very old and should be be used and instead use something newer like 9.1 which is currently used in the dockerfile.

Is it safe to remove jruby 1.7.8 and add jruby9.1 from the travis file?

**Comment by logicminds** [comment]
@glennsarti Was this fixed?  #241 will not pass tests with the old jruby version.

**Comment by logicminds** [comment]
@stahnma Can we drop jruby 1.7.8 as we cannot safe load yaml which is a security flaw?  Replace with jruby 9k?

**Comment by mattkirby** [comment]
We should be able to drop jruby 1.7.8 in favor of 9k. I've opened a PR, #247, and the jruby tests appear to pass fine so it seems reasonable to me.

**Comment by mattkirby** [comment]
#247 has been merged so jruby 1.7.8 should no longer be an issue here.
