### ISSUE TITLE
NilClass error when running API without Graphite configured

### ISSUE THREAD

**Issue by fatmcgav** [puppetlabs/vmpooler#81]
If you attempt to use the API without Graphite configured, you get a 'undefined method [] for NilClass' error, due to [api.rb#L14](https://github.com/puppetlabs/vmpooler/blob/master/lib/vmpooler/api.rb#L14)

PR incoming to fix :)

**Comment by mattkirby** [comment]
I believe this is resolved with the addition of a dummy stats provider.
